CREATE TABLE IF NOT EXISTS PUBLIC.PRODUCT (
    ID UUID NOT NULL,
    CODE VARCHAR(10),
    DESCRIPTION VARCHAR(255),
    PRICE DECIMAL(10, 2),
    CREATE_DATE TIMESTAMP,
    UPDATE_DATE TIMESTAMP,
    CONSTRAINT PRODUCT_PK PRIMARY KEY ("ID"),
    CONSTRAINT "PRODUCT_CODE_UK" UNIQUE  ("CODE")
);

CREATE TABLE IF NOT EXISTS PUBLIC.CUSTOMER (
    ID UUID NOT NULL,
    DOCUMENT VARCHAR(14) NOT NULL,
    "NAME" VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255),
    PHONE_NUMBER VARCHAR(255),
    CREATE_DATE TIMESTAMP,
    UPDATE_DATE TIMESTAMP,
    CONSTRAINT CUSTOMER_PK PRIMARY KEY ("ID"),
    CONSTRAINT "CUSTOMER_DOCUMENT_UK" UNIQUE  ("DOCUMENT")
);

CREATE TABLE IF NOT EXISTS PUBLIC.BUY_ORDER (
    ID UUID NOT NULL,
    "NUMBER" NUMERIC NOT NULL,
    STATUS ENUM('ORDER_PLACED', 'AWAITING_PAYMENT', 'PAID_ORDER', 'INVOICED', 'ORDER_SEPARATION', 'ORDER_SENT', 'ORDER_DELIVERY', 'ORDER_READY_PICKUP', 'ORDER_CANCELED'),
    CUSTOMER_ID UUID NOT NULL,
    CREATE_DATE TIMESTAMP,
    UPDATE_DATE TIMESTAMP,
    CONSTRAINT BUY_ORDER_PK PRIMARY KEY ("ID"),
    CONSTRAINT "BUY_ORDER_NUMBER_UK" UNIQUE  ("NUMBER")
);

CREATE TABLE IF NOT EXISTS PUBLIC.ITEM (
    ID UUID NOT NULL,
    BUY_ORDER_ID UUID NOT NULL,
    PRODUCT_ID UUID NOT NULL,
    AMOUNT INTEGER NOT NULL,
    UNIT_PRICE DECIMAL(10, 2),
    FULL_DISCOUNT DECIMAL(10, 2),
    CREATE_DATE TIMESTAMP,
    UPDATE_DATE TIMESTAMP,
    CONSTRAINT ITEM_PK PRIMARY KEY ("ID")
);

ALTER TABLE PUBLIC.BUY_ORDER ADD CONSTRAINT "BUY_ORDER_CUSTOMER_FK" FOREIGN KEY ("CUSTOMER_ID") REFERENCES PUBLIC.CUSTOMER("ID");
ALTER TABLE PUBLIC.ITEM ADD CONSTRAINT "ITEM_BUY_ORDER_FK" FOREIGN KEY ("BUY_ORDER_ID") REFERENCES PUBLIC.BUY_ORDER("ID");
ALTER TABLE PUBLIC.ITEM ADD CONSTRAINT "ITEM_PRODUCT_FK" FOREIGN KEY ("PRODUCT_ID") REFERENCES PUBLIC.PRODUCT("ID");